### ISSUE TITLE
help command restart service

### ISSUE THREAD

**Issue by dckiller51** [kvj/hass_openwrt#16]
Hello, I have a problem successfully restarting a service. I think my configuration is not good.
Besides, with the addition of the file lines I lose access. API error

hass.json

```
{
  "hass": {
    "description": "Home Assistant OpenWrt integraion permissions",
    "read": {
      "ubus": {
        "network.wireless": ["status"],
        "network.device": ["status"],
        "iwinfo": ["info", "assoclist"],
        "hostapd.*": ["get_clients", "wps_status"],
        "system": ["board"],
        "mwan3": ["status"]
      },
    },
    "write": {
      "ubus": {
        "system": ["reboot"],
        "hostapd.*": ["wps_start", "wps_cancel"]
		"file": ["exec"]
      },
      "file": {
        "/etc/init.d/presence-detector": ["exec"]
      }
    },
  }
}
```
command test homeassistant

```
service: openwrt.exec
data:
  command: service presence-detector restart
target:
  entity_id: binary_sensor.openwrt_wifiap_02
```
